export const funFacts = [
  "Honey never spoils. Archaeologists have found pots… over 3,000 years old and still perfectly edible.",
  "Cows have best friends and can become stressed when they are separated.",
  "Bananas are berries, but strawberries aren't.",
  "The shortest war in history was between Britain an… 27, 1896. Zanzibar surrendered after 38 minutes.",
  "The average person spends six months of their life waiting for red lights to turn green.",
  "The world's largest desert is Antarctica.",
  "The Eiffel Tower can be 15 cm taller during the summer due to thermal expansion.",
  "A group of flamingos is called a 'flamboyance.'",
  "Penguins can jump up to 6 feet in the air.",
  "The longest English word without a vowel is 'rhythms.'",
  "The Great Wall of China is not visible from the Moon without aid.",
  "A single cloud can weigh more than 1 million pounds.",
  "Oxford University is older than the Aztecs.",
  "Coca-Cola was originally green.",
  "The world's largest pizza was 131 feet in diameter.",
  "Banging your head against a wall burns 150 calories per hour.",
  "A small child could swim through the veins of a blue whale.",
  "A 'jiffy' is an actual unit of time. It is 1/100th of a second.",
  "Kangaroos can't hop backward.",
  "Octopuses have three hearts.",
  "The world's oldest known recipe is for beer.",
  "Cats have five toes on their front paws but only four toes on their back paws.",
  "The longest recorded flight of a chicken is 13 seconds.",
  "The state of Florida is larger than England.",
  "The smell of freshly-cut grass is actually a plant distress call.",
  "A group of owls is called a parliament.",
  "A day on Venus is longer than a year on Venus. It …s on its axis more slowly than it orbits the sun.",
  "A newborn kangaroo is the size of a lima bean.",
  "The first computer programmer was a woman named Ada Lovelace.",
  "Honeybees can recognize human faces.",
  "The average person will spend six months of their life waiting for red lights to turn green.",
  "A single strand of spaghetti is called a 'spaghetto.'",
  "The inventor of the frisbee was turned into a fris…s ashes were molded into a frisbee after he died.",
  "Venus is the hottest planet in our solar system, even though Mercury is the closest to the sun.",
  "A day on Pluto is shorter than a day on Earth.",
  "The world's largest flower, the Rafflesia arnoldii, can grow up to three feet in diameter.",
  "There are more possible iterations of a game of chess than there are atoms in the known universe.",
  "The electric chair was invented by a dentist.",
  "The longest recorded hiccuping spree lasted 68 years.",
  "The longest word in the English language without a vowel is 'rhythms.'",
  "The longest hiccuping spree lasted 68 years.",
  "The world's oldest known joke is from 1900 BC Sumeria.",
  "The first known use of the hashtag symbol (#) was in a tweet by Chris Messina in 2007.",
  "The oldest known written recipe is for beer and dates back to around 5,000 BC.",
  "The fingerprints of a koala are virtually indistinguishable from humans.",
  "A 'billion' used to mean a million million (1,000,… now it means a thousand million (1,000,000,000).",
  "Hawaii is the only U.S. state that commercially grows coffee.",
  "The Earth's core is hotter than the surface of the sun.",
];
